Repository LeonardoDecaris/TechAcademy6_Dev, pull requests merged in 2025-06, with the labels that each got.

#1 chore(commit): adicionando o commitlint no frontend
  FrontEnd/.husky/commit-msg
  FrontEnd/commitlint.config.js
  FrontEnd/package-lock.json
  FrontEnd/package.json
Labels: enhancement

#3 feat(nginx):criacao do certificado
  Nginx/Dockerfile
  Nginx/nginx.conf
  Nginx/openssl-san.cnf
  docker-compose.yml
Labels: enhancement

#4 feat(docker): ajuste de .env
  BackEnd/db/ScriptSQL_Inicial.txt
  BackEnd/db/dumpInicial.sql
  FrontEnd/.husky/commit-msg
  FrontEnd/.husky/pre-commit
  FrontEnd/commitlint.config.js
  FrontEnd/notas.txt
  docker-compose.yml
Labels: enhancement

#5 Feature/commitlint
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement

#8 V2.0.0
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  BackEnd/db/ScriptSQL_Inicial.txt
  BackEnd/db/dumpInicial.sql
  FrontEnd/.husky/commit-msg
  FrontEnd/.husky/pre-commit
  FrontEnd/notas.txt
  FrontEnd/tests/adminTest.spec.ts
  FrontEnd/tests/anotacoes
  FrontEnd/tests/developersPage.spec.ts
  FrontEnd/tests/homeTest.spec.ts
  FrontEnd/tests/loginTest.spec.ts
  FrontEnd/tests/navBarTest.spec.ts
  FrontEnd/tests/registerLoginTest.spec.ts
  FrontEnd/tests/soundPage.spec.ts
  FrontEnd/tests/tests.spec.ts
  FrontEnd/tests/userSettingsPage.spec.ts
  Nginx/Dockerfile
  Nginx/nginx.conf
  Nginx/openssl-san.cnf
  commitlint.config.js
  docker-compose.yml
  package-lock.json
  package.json
Labels: bug, documentation, enhancement

#10 fix(commit-msg): correcao no commit
  .husky/commit-msg
Labels: bug

#11 Hotfix/testes correcao
  .husky/commit-msg
  FrontEnd/playwright.config.ts
  FrontEnd/tests/tests.spec.ts
Labels: enhancement

#12 Develop
  .husky/commit-msg
  FrontEnd/playwright.config.ts
  FrontEnd/tests/tests.spec.ts
Labels: bug, enhancement
